vlang/ui

.github/workflows/ci.yml
ui_linux.v

Based on https://gtk-rs.org/docs/gtk/struct.MessageDialog.html , with some
modifications to actually *destroy* the dialog, when it is not needed.

linux: add a gtk3 based message_box/1 implementation

---

button.v
canvas.v
checkbox.v
key.v
label.v
menu.v
picture.v
progressbar.v
radio.v
slider.v
textbox.v
ui.v
window.v

I have added a fully functional multi-orientation slider. It supports:
* Dragging
* Move to clicked point
* Vertical/Horizontal Orientations
There is no support for:
* Ticks (will be added soon)
* Tooltip (had added it but removed it due to hacky impl)
All values are in `f32` so fairly precise. 
I had planned on making the thumb round but unfortunately v's `gg` doesn't support `draw_circle` function yet so had to fall back to `draw_rect`.
Working on an example for basic usage.

add slider control

---

key.v
textbox.v

This PR adds text selection by keyboard and mouse.
Holding shift and using arrow keys will select one letter forward or backward.
Holding ctrl+shift and using arrow keys will select until the next whitespace in the respective direction.
Selection with mouse is as usual.

add text selection by keyboard and mouse

---

key.v
textbox.v

This PR adds CTRL+Backspace functionality to erase whole words quickly.

make ctrl + backspace work

---

window.v

On my system, system_font_path takes ~156ms, and while it is running,
the window is already displayed, but with black content. This resulted
in annoying flashing.
Moving system_font_path before window initialization, makes the flashing
nearly invisible.

move system_font_path call before window creation to minimize blinking at start

---

dropdown.v

Change the `text` property to `pub` to avoid access error:
`cannot refer to unexported field text(typeui.DropdownItem)`
Example:
```v
fn dropdown_method_changed(app mut App, dd &ui.Dropdown) {
item := dd.items[dd.selected_index]
app.method = item.text
}
```

Change DropdownItem text property to public

---

slider.v

Sliders are not drawn from the middle of the "position", this PR fix it

Fix slider position (keep them in the middle of the position)

---

ui_windows.v

`message` argument should be also LPCTSTR.

fix message box on windows, part 2

---

button.v
canvas.v
checkbox.v
dropdown.v
group.v
label.v
menu.v
picture.v
progressbar.v
radio.v
rectangle.v
slider.v
stack.v
switch.v
textbox.v
transition.v

This PR is unified interface arguments.
```
pub interface IWidgeter {
init(ILayouter)
...
}
```
Above is interface defines, so we should change `fn (b mut Button) init(p &ILayouter) {` to `fn (b mut Button) init(parent ILayouter) {`.

Unified interface arguments

---

examples/change_title.v

Move assigning `onclick` listener back.

examples: fix change_title

---

examples/counter.v

Move assigning `onclick` listener back.

examples: fix counter

---

examples/timer.v

The example still does not work (the window closes immediately after it's displayed).

examples: fix building timer

---

.github/workflows/ci.yml

- Removed unused `libgtk-3-dev` dependency
This dependency was used for MessageBox on Linux, now it's useless.
- Removed unused workaround to fix broken MS `apt-get` source lists
Seems like they fixed their issue, as everything can be installed w/o errors.
- Used `setup-freetype` tool to install `freetype` on Windows

ci: clean up workflow

---

examples/timer.v

- Fixed the example
- Fixed warnings
- Reformatted code with `v fmt`
- Used string interpolation to show elapsed seconds
This resolves an issue where elapsed seconds were displayed in an exponential form.

examples: fix timer example

---

.gitignore
examples/change_title.v

This PR satisfies the compiler's complaint (V `0.1.27` 7c9bb44)
```sh
~> v run examples/change_title.v
examples/change_title.v:15:14: warning: reference field `App.window` must be initialized 
13 | 
14 | fn main() {
15 |     mut app := &App{
|                 ~~~~
16 |         title_box: ui.textbox(
17 |             max_len: 20
```
Additionally it appends its binary to `.gitignore`

examples: fix uninitialized App.window reference field on change_title.v

---

ui.v

Fixes a BUNCH of compile errors when trying to build the examples directory. However I'm not sure the reason why this was originally not made mutable.
Addresses https://github.com/vlang/ui/issues/150

Make FreeType and GG public and mutable on UI struct

---

examples/build_examples.vsh

`.` as relative path refers to the current working dir.
E.g. running `v run examples/build_examples.vsh` also tried to compile all UI .v files

Allow running build_examples.vsh from a different working dir

---

ui.v
v.mod

This brings the version number in `v.mod` and `ui.v` back in line with the README.

v.mod, ui.v: Bump version to 0.0.3

---

.github/workflows/ci.yml

@medvednikov this makes the windows pipeline pass too

ci: set -skip-path for windows V build

---

.github/workflows/ci.yml

On Ubuntu `libglfw3-dev` seems to be needed, otherwise the job fails:
`/home/runner/work/v_ui/v_ui/thirdparty/sokol/sokol_app.h:5482:10: fatal error: X11/extensions/Xrandr.h: No such file or directory`

ci: remove glfw

---

examples/build_examples.vsh

- remove `os` import as this was fixed in V
- try to build all examples before exiting in case of error (allows to catch multiple problems in one run)

build_examples.vsh: remove os import; handle build errs at program end

---

ui.v

This PR also removes the obsolete tmp_save_pic calls, that stored each
memory image in a file first, and loaded it instead.

cleanup: use gg.create_image_from_memory/2

---

ui.v

With this PR, the image is not flipped on linux:

ui: remove ui init(), stbi.set_flip_vertically_on_load(true) not needed any more

---

.github/workflows/ci.yml

I created this to catch things like https://github.com/vlang/v/pull/6178 more early.

ci: build users.v with -prod on all OSes

---

examples/group.v
group.v

This PR brings the way `group` children are declared in line with other widgets like `row`, `column`, `window`.
**Before**
```v
ui.group({
children: []
})
```
**After**
```v
ui.group({}, [
// children
])
```
I also vfmt'ed `group.v ` and `examples/group.v`.

group: unify children declaration

---

button.v
canvas.v
checkbox.v
dropdown.v
group.v
label.v
listbox.v
menu.v
picture.v
progressbar.v
radio.v
rectangle.v
slider.v
stack.v
switch.v
textbox.v
transition.v
window.v

Due to a lots of copy paste the argument names in many functions were different and not even related to the widget name.
Now the arguments are in most cases the first letter of the widget name.
_I thoroughly checked that no new issues show up._

Unify function argument names

---

examples/group.v
group.v

**Fixes**
- recalculate the group children positions in `group.set_pos()`
- use the actual window color for the title background
**Before**
**After**

group: multiple fixes

---

group.v

- use actual space reserved for the title for width calculation
- draw no title if the group is really really small (prevent panic in substr() call)

group: title fixes

---

button.v

Currently there are false warnings for every button created.

button: hide icon_path warning when path is not specified

---

window.v

Needed so that `./v run ~/.vmodules/ui/examples/users.v` works.

fix ui compilation with V 0.1.29 b44620d

---

ui.v
window.v

1) Since MouseEvent.button is integer, changed to enum MouseButton.
2) for importing just ui module, copied from sapp.MouseButton to ui.MouseButton.

ui: add enum MouseButton for MouseEvent

---

ui.v
window.v

1) changed type of `ui.MouseEvent.mods` from `int` to `ui.KeyMod` which is also used in `ui.window_key_down()` method.
2) set `ui.MouseEvetn.mods` value `ui.window_mouse_down()` etc returns.

ui: change MoueEvent.mods from int to enum KeyMod

---

const.v
window.v

Add `ui.events.on_resize` event to `ui.Window`.
Setting `ui.Window.resizable = true` publishes `on_resize` event.

add on_resize event to window

---

ui.v

This PR fixes errors of os.exec() without or_block in ui.v.

fix error of os.exec() without or_block

---

dropdown.v
examples/dropdown.v

Added a new function to [dropdown.v](https://github.com/vlang/ui/blob/master/dropdown.v), selected(), which returns the currently selected DropdownItem.
selected():
```v
// Returns the currently selected DropdownItem
pub fn (dd &Dropdown) selected() DropdownItem {
return dd.items[dd.selected_index]
}
```
Also made a minor fix in the same file, on which selecting an element by pressing enter didn't call dd.on_selection_changed() (if this function is present, that is).
Finally, I edited the dropdown example to show this new function, and vfmt-d both files.

dropdown.v: added selected() function

---

button.v
checkbox.v
column.v
const.v
examples/calculator.v
examples/change_title.v
examples/counter.v
examples/dropdown.v
examples/group2.v
examples/rgb_color.v
examples/slider.v
examples/slider_textbox.v
examples/switch.v
examples/temperature.v
examples/timer.v
examples/users.v
label.v
progressbar.v
radio.v
row.v
slider.v
stack.v
textbox.v
transition.v
ui.v
ui_extra_align.v
ui_extra_debug.v
ui_extra_size.v
webview/webview.v
window.v

* This PR fixes the issue introduced with propose_size for widgets. The default is now again to have the children at their initial size when children are not all layouts.
* Examples have also be updated to use the design with widths, heights and alignements.

introduce ui.compact to inherit size from children

---

examples/timer.v
ui.v

fix obsolete references to time.sleep_ms and time.usleep

---

README.md

This is a follow-up to [issue 316](https://github.com/vlang/ui/issues/316) which proposes a solution for developing with v/ui on ChromeOS.

add a note on ChromeOS dependencies

---

ui_extra_size.v

Enums used outside of modules should be public. And this is required to fix below error
https://github.com/vlang/v/pull/9788/checks?check_run_id=2378437285#step:16:1

make WindowSizeType public

---

stack.v

This is a small fix that makes `ui` compile with [PR #9873](https://github.com/vlang/v/pull/9873).

make ui compile with PR #9873

---

listbox.v
stack.v
transition.v

This adds some `unsafe` wrappers to allow compilation after vlang/v PR [10033](https://github.com/vlang/v/pull/10033) is merged.

fix for vlang/v PR #10033

---

ui_extra_debug.v
window.v

This will be required once automatic string to C string conversation is removed.
See https://github.com/vlang/v/pull/10140
This isn't necessary for this PR, but will produce warning once it is merged.

use C string explicitely

---

window.v

Re-enable the `on_mouse_down` callback as currently there is no alternative.
Regression in: https://github.com/vlang/ui/commit/0f6474493fe45c89134e55b2b43f203d42e47e18

fix on_mouse_down

---

examples/demo_row_layout.v
examples/rgb_color.v
examples/slider_textbox.v
examples/temperature.v
examples/users_resizable.v
window.v

`$if android { font_path = 'fonts/RobotoMono-Regular.ttf'` always requires `assets/fonts/RobotoMono-Regular.ttf` to be present.
But Android only requires `assets/foo_font.ttf` for custom font if needed.
And `gg.system_font_path()` correctly gets system font.
So removed what leads to confusion.
This fixes https://github.com/Larpon/jni/issues/7#issuecomment-908591761
Fixed some code-style issues.

fix android default font path

---

ui_settings.v

For Android it can not even compile since Vab can't handle cJson.
It's not a good thing to leave such a serious bug uncorrected long time, so temporarily disabled it until fixed.

settings: diable setting temporarily

---

label.v

Enabled `Label.point_inside()`

label: enable point_inside()

---

extra_event_mngr.v
widget_canvaslayout.v
window.v

This adds the following shapes:
- `draw_triangle_empty()`
- `draw_square_empty()`
- `draw_square_filled()`
- `draw_circle_empty()`
- `draw_arc_filled()`
- `draw_arc_empty()`
Slight reordering and organizing as well.

Add remaining CanvasLayout shapes

---

webview/webview_windows.c.v

When compiling with V on a different drive than the system drive, the include directory would not be set properly.
Using the environment-variable `SystemDrive` (in your implementation case sensitive) could be used to properly determine the location.

Fixed Include Path for `<EventToken.h>` when V is not installed on the System Drive. 

---

widget_menu.v

Proof of concept to make the menuitem adjust to the text size. 
The adjustement assumes a fixed sized font (or make the font_size param large enough.   
The code is a proof of concept and has a known bugs: The sub-menu don't align correctly (see the end of the screenshot).
It should be easy to add a setting to have fixed-width menu item and compact ones (...once the bug is fixed)

[Improvement] Make the menu item compact

---

README.md

This PR update readme snippet identation to use 4 spaces. The difference is how github render the readme, see below:
Before: 
After: 
Feel free to accept or drop this PR. Cheers :beers:

Update snippet identation

---

src/ui_android.c.v

Fixes this compile error:
```
v -os android -nocache -cg -d no_load_styles -cc clang -dump-modules "/tmp/v.modules" -dump-c-flags "/tmp/v.cflags" ~/.vmodules/ui/examples/rectangles.v
...
~/Projects/v/vlib/gg/gg_android_outside_termux.c.v:17:53: error: field `os.NativeActivity.assetManager` is not public
15 |     config := C.AConfiguration_new()
16 |     activity := &os.NativeActivity(sapp.android_get_native_activity())
17 |     C.AConfiguration_fromAssetManager(config, activity.assetManager)
|                                                        ~~~~~~~~~~~~
18 |     density := C.AConfiguration_getDensity(config)
19 |     C.AConfiguration_delete(config)
```

android: use os.NativeActivity

---

src/interface_drawtextwidget.v
src/style_button.v
src/style_checkbox.v
src/style_dropdown.v
src/style_label.v
src/style_layouts.v
src/style_progressbar.v
src/tool_settings.v

From https://github.com/vlang/v/pull/17197, fix variable naming to prevent import symbol shadowing.

Fix naming to prevent shadowing

---

src/menu.v
src/textbox.v
src/textbox_textview.v

This PR introduces a potentially dirty fix. When items are added to the menu dynamically, them menu size wasn't updated. This PR change - is to call `update_size` function from `add_item` function after item was added

fix: `menu` size doesn't update when items added dynamically

---

src/menu.v
src/textbox.v
src/textbox_textview.v

This PR implements `get_items_count` public function. This function is needed when UI logic depends on the current count of items in the menu.

Implement `get_items_count` menu function

---

src/textbox.v
src/textbox_textview.v
src/window.v

This PR introduces a change to the handling of delegated events when there are selected widgets with higher z-index than delegated widgets. This is the case when using both menubar with submenus and gg canvas - previously, events will be always redirected to canvas even if a higher menu button was selected.

fix: handling of delegated events

---

component/gg_app.v
src/textbox.v
src/textbox_textview.v

This PR adds `z-index` field to `GGComponentParams` structure, and uses this field when creating `CanvasLayout` in `gg_canvaslayout` function.

Add z index parameter to `GGComponentParams`

---

src/stack.v
src/textbox.v
src/textbox_textview.v

Currently, the Stack (column/row) calculates it's z-index based on children's z-index. Stack will have `z-index = child_with_biggest_z_index - 1`, which is wrong since a Stack can have children with different z-index and a Stack must have the lowest z-index to not cover children.
As an example, I have the following UI setup
```v
app.window = ui.window(
width: 600
height: 600
title: 'Polygon Editor'
children: [
ui.column(
id: 'test'
children: [
ui.menubar(
height: 30
z_index: 2
items: [
ui.menuitem(
id: 'file_menu_button'
text: 'File...'
action: open_file_menu
),
]
),
ui.menu(
id: 'file_menu_dropdown'
z_index: 2
),
gg_canvaslayout(
app: viewport_app
z_index: 1
),
]
),
]
)
```
Both `menubar` and `menu` widgets must be above `gg_canvaslayout`, and `gg_canvaslayout` must be above `column` …

fix: Stack widget should have lower z-index than child with the lowest z-index

---

src/button.v
src/canvas.v
src/dropdown.v
src/extra_debug.v
src/extra_text.v
src/grid.v
src/interface_scrollable.v
src/label.v
src/layout_box.v
src/layout_canvas.v
src/layout_group.v
src/listbox.v
src/menu.v
src/picture.v
src/progressbar.v
src/radio.v
src/rectangle.v
src/slider.v
src/stack.v
src/subwindow.v
src/switch.v
src/textbox.v
src/tool_text_style.v
src/transition.v
src/window.v

This PR renames variables and parameters to prevent module name shadowing. Related to: https://github.com/vlang/v/pull/18118
I mostly opted for `gui`. On master current handlings to not shadow the `ui` module are `gui` and `u`. Please let me know what you prefer, some quick changes are no work. 
https://github.com/vlang/ui/blob/417db89c2b771601c88404399cc144a01e8716e8/src/ui.v#L66
https://github.com/vlang/ui/blob/417db89c2b771601c88404399cc144a01e8716e8/src/tool_text_style.v#L128

refactor: rename vars and params to prevent module name shadowing

---

src/picture.v

https://github.com/vlang/v/pull/19015 made `gg.Context` mutable for `create_image` method. This causes CI checks in V repo to fail for this PR.
This PR introduces "non-invasive" fix to V UI to make CI on V repo pass

Address breaking changes introduced in #19015 in V repo

---

.github/workflows/ci.yml
.github/workflows/lint.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml

windows example builds in #546 are failing because of suboptimal ci.
lets update the ci first.
comparison:
- current: https://github.com/vlang/ui/actions/runs/6490440566
- suggestion: https://github.com/vlang/ui/actions/runs/6490805956?pr=547

ci: update workflows

---

examples/build_examples.vsh

- adds shebang to allow to run int a script without prefix
- makes execution of the script directory independent
- execute over system as it currently enables to Ctrl-c out of the scripts execution

examples: update `build_examples.vsh`

---

.gitattributes

should fix recognising .vsh as glsl

chore: update gitattributes to recognize V language for `.vsh` files

---

src/draw_device_bitmap.v
src/draw_device_print.v
src/draw_device_svg.v

This PR needed to make tests pass in vlang/v#19809

use the builtin consts for `max_i32` and `min_i32`, instead of the constants defined in `math`

---

src/window.v

When the form is dragged from one monitor to another with different dpi settings (or scale on windows) the form was not sized correctly. This change updates the scal factor when the form is moved.

Handle dpi changes

---

component/tabs.v

Wrapped labels inside a `row` to position theses instead of labels.
For some reasons the `.set_pos()` method is not working on labels directly so the trick is to set position of a parent, that's why we wrap labels into `row` (we could also use `column`)

Fix tabs titles

---

component/tabs.v
src/interface_scrollable.v

I noticed that with a big element the scrollbar size becomes so small we can't see it anymore
Changing a few lines fix this by using the max function and a const min size for the scroll thumb

Add minimal size to scrollbar thumb

---

src/picture.v

This pull request corrects the condition that tests if the picture widget should use the resource cache to store images.
Not using the cache will result in sokol exhausting its sampler pool after many images are loaded. Once exhausted, sokol emits the following message:
```
sokol_gfx.h, line: 17257, message: SAMPLER_POOL_EXHAUSTED: sampler pool exhausted
```
After several of these message are emitted, sokol faults.

UI: change test condition of pic.use_cache to test for true

---

src/picture.v

Adds a method to remove images in the resource cache that the Picture widget uses to cache images.
This is needed for long running apps that load many images and then later discard them. Overtime, these cached images causes the memory footprint of the host app to increase.

UI: Add method to Picture widget to selectively remove images from cache

---

src/interface_scrollable.v

Many of the examples in `examples/` (e.g. demo_scrollview.v) will immediately fault when compiled with the `-prod` flag. I've also seen similar faults in my own project, `github/mike-ward/Kite`. I found that the faults consistently occurred in functions that used generic parameters in `Interface_Scrollable.v`.
Using a debugger and some printf statements, I determined that pointers in these methods were sometimes corrupt, although I could never deduce why. The corruptions only occurred when building with the `-prod` flag.
I noticed that the functions in question could have their generic parameters replaced with `ScrollableWidget`. After making this change, most of the example programs no longer faulted when built with the `-prod` flag. A few examples, notably, …

UI: Replace generic parameters with ScrollableWidget

---

src/layout_group.v

Fix the position error when the layout_group child widget is an AdjustableWidget.
Refer to stack.v set_child_pos method

Fix the position error when the layout_group child widget is an AdjustableWidget

---

src/textbox_textview.v

Greatly improved the cursor movement using the keyboard in multiline textboxes.
Support for:
- quickly jumping over words (ctrl + direction)
- quickly selecting words (ctrl + shift + direction)
- deleting entire words using the delete key (ctrl + delete)
This also fixes a crash when pressing delete at the end of the text.

Better multiline textbox cursor movement using the keyboard
