vlang/ui

- .gitignore
- button.v
- checkbox.v
- examples/users/users.v
- label.v
- picture.v
- progress_bar.v
- radio.v
- textbox.v
- window.v
Makes it work like this: 
Needs https://github.com/vlang/v/pull/3412 .
> Linux fixes.

- v.mod
This PR adds a v.mod file, so that this module can be manipulated by vpm and vpkg.
> Add a v.mod file (needed by v install)

- examples/counter/counter.v
This adds a basic counter example
> add counter example

- examples/temprature/temprature.v
- key.v
- textbox.v
I have added the Celsius <-> Fahrenheit converter. Had to add `on_key_up` & `on_key_down` events to `TextBox`.
> add temprature converter

- examples/timer/timer.v
This is a timer example as part of the 7GUIs.
> add timer example

- examples/slider/slider.v
Example for vertical & horizontal slider.
> add slider example

- slider.v
This PR fixes the slider so that it works properly.
> Fixes for slider

- examples/users/users.v
- slider.v
- window.v
> ui: eliminated warnings

- button.v
- canvas.v
- checkbox.v
- dropdown.v
- label.v
- menu.v
- picture.v
- progressbar.v
- radio.v
- slider.v
- textbox.v
- ui.v
Fixed enum warnings by changing them from UpperCamelCase to lower_snake_case .
> WidgetType casing: .Button -> .button, etc (UpperCamelCase -> lower_snake_case)

- examples/transitions.v
Sorry for the confusion. My git-fu failed me
> examples: Use a const of 158 for picture dimensions

- radio.v
- textbox.v
This should fix all issues with textbox selection. Tested on Linux.
> TexBox Selection Fixes

- label.v
> Added multi line support to label

- .gitignore
- examples/calculator.v
- examples/message.v
- key.v
- ui.v
- ui_linux.v
This PR implements a simple modal message box on linux, using v ui itself.
> message_box: a new linux implementation using ui itself

- README.md
I couldn't get this to work locally ... until I realized that I was using an old version of V. I added 
```
v up
```
to the install making it clear that you need a recent version. hopefully it saves others time.
> modest readme.md change

- examples/rectangles.v
- window.v
This PR fixes some compilation warnings, and makes UI use slightly less memory for
new events.
> Minimize memory usage in UI when new events happen.

- .gitignore
- examples/resizable_window.v
- stack.v
- ui.v
- window.v
add resizable callback for the window.
@thecodrr How to implement resize next, I want to hear your opinion. My immediate idea is to add a type to determine whether the current widget is a layout.
> add resizable callback for the window

- button.v
- canvas.v
- checkbox.v
- dropdown.v
- group.v
- label.v
- menu.v
- picture.v
- progressbar.v
- radio.v
- rectangle.v
- slider.v
- stack.v
- switch.v
- textbox.v
- transition.v
- ui.v
- window.v
rename get_size() to size() for convention
> code fix: rename get_size() to size()

- examples/calculator.v
- examples/counter.v
- examples/dropdown.v
- examples/group.v
- examples/rectangles.v
- examples/resizable_window.v
- examples/slider.v
- examples/switch.v
- examples/temperature.v
- examples/timer.v
- examples/transitions.v
- examples/users.v
change type cast way from `as IWidget` to `IWidget(...)`
> compile error: change type cast way from `as IWidget` to `IWidget(...)`

- ui.v
Remove space in NotoSans-Regular font name.
> fix NotoSans-Regular font name

- textbox.v
This PR modify deprecated function in `textbox.v`.
- Change `is_white` to `is_space`.
> textbox: modify deprecated function

- .editorconfig
Ref https://github.com/vlang/v/pull/3859.
> Add trim_trailing_whitespace to .editorconfig

- button.v
- canvas.v
- checkbox.v
- dropdown.v
- group.v
- label.v
- menu.v
- picture.v
- progressbar.v
- radio.v
- rectangle.v
- slider.v
- stack.v
- switch.v
- textbox.v
- transition.v
This PR fix interface arguments usage.
```v
pub interface IWidgeter {
init(ILayouter)
...
}
```
Above is interface defines, so we should change `fn (b mut Button) init(p &ILayouter) {` 
to `fn (b mut Button) init(parent ILayouter) {`.
> fix interface usage

- .github/workflows/ci.yml
- .gitignore
- examples/calculator.v
- examples/counter.v
- examples/dropdown.v
- examples/group.v
- examples/rectangles.v
- examples/resizable_window.v
- examples/slider.v
- examples/switch.v
- examples/temperature.v
- examples/timer.v
- examples/transitions.v
- examples/users.v
- ui.v
- ui_linux.v
This PR enables CI testing with MSVC again.
> bugfix: msvc does not like C double casts, use a casting function instead.

- examples/change_title.v
- window.v
This PR implement `window.set_title` and add `change_title.v` example.
> Implement window.set_title and add test example

- ui.v
This PR fix the error that import `filepath`.
> Fix the error that import filepath

- ui.v
This PR change `os.join` to `os.join_path`.
> os.join => os.join_path

- ui.v
This PR change `os.tmpdir` to `os.temp_dir`.
> os.tmpdir => os.temp_dir

- checkbox.v
- examples/rgb_color.v
- examples/slider.v
- examples/slider_textbox.v
- rectangle.v
- slider.v
- textbox.v
- window.v
- slider widget fixes and add/changes, refer to slider.v update comments
- update rectangle widget
- window.v fix to get correct mouse position on mouse movement
- examples : fix slider.v 
add slider_textbox.v  example
add rgb_color.v example
> Slider widget update

- dropdown.v
- examples/rectangles.v
- radio.v
- slider.v
- textbox.v
- window.v
Fixes to compile and run rectangles.v with latest v on MacOS
> rectangles: fixes to run with latest v

- button.v
- checkbox.v
- dropdown.v
- group.v
- label.v
- listbox.v
- menu.v
- picture.v
- progressbar.v
- radio.v
- rectangle.v
- slider.v
- stack.v
- switch.v
- textbox.v
- transition.v
- window.v
This PR fix warning of reference field not initialized.
> warning: fix warning of reference field not initialized

- examples/calculator.v
- examples/change_title.v
- examples/counter.v
- examples/dropdown.v
- examples/group.v
- examples/resizable_window.v
- examples/rgb_color.v
- examples/slider.v
- examples/slider_textbox.v
- examples/switch.v
- examples/temperature.v
- examples/timer.v
- examples/transitions.v
- examples/users.v
- ui_linux.c.v
This PR modify examples with new syntax.
- Modify examples with new syntax.
- Correct array init `[]type{}`.
> examples: modify examples with new syntax

- examples/slider.v
Move assigning `on_value_changed` property back.
> examples: fix slider example

- examples/switch.v
> examples: improve switch example

- examples/temperature.v
- Fixed warnings
- Formatted with `vfmt`
- Moved `on_key_up` listeners back
> examples: fix temperature example

- README.md
Setup `freetype` with V `setup-freetype` tool.
> readme: update instructions for Windows

- button.v
- canvas.v
- checkbox.v
- dropdown.v
- examples/calculator.v
- examples/users.v
- group.v
- label.v
- listbox.v
- menu.v
- picture.v
- progressbar.v
- radio.v
- rectangle.v
- slider.v
- stack.v
- switch.v
- textbox.v
- transition.v
- ui.v
- window.v
This PR modify all files to `(mut f Foo)` syntax.
> all: modify to `(mut f Foo)` syntax

- .gitignore
- ui_linux.c.v
- Also added VS Code workspaces to gitignore
> linux: fix message_app is not marked as mut

- .gitignore
Ignore build binaries for all examples with wildcards similar to V repo.
> Ignore example binaries using wildcards

- .gitignore
- examples/transitions.v
- picture.v
This PR includes a click function for pictures
> Added click function for pictures

- examples/change_title.v
- examples/dropdown.v
- examples/resizable_window.v
- examples/rgb_color.v
Initialize the struct values that otherwise give a warning.
> examples: fix warnings

- README.md
add missing open curly brace at ui.row on line 18
> add missing open curly brace at ui.row on line 18 of README.md

- button.v
- rectangle.v
- textbox.v
Fixes CI in vlang/v#6161. GitHub won't let me reopen the previous PR for some reason.
> ui: remove default sizes

- examples/build_examples.vsh
If this PR and https://github.com/vlang/v/pull/6170 get merged the UI pipeline will pass again.
> build_examples: build webview only on macos for now

- row.v
- stack.v
There are still lots of issues with rows and columns, but  this is a good starting point.
> stack: small refactor and fix of children size calculation

- examples/group2.v
Group example with more complexity.
> examples: create group2.v

- group.v
> group: shorten title if group width is to small

- rectangle.v
> run fmt for rectangle.v

- window.v
This requires https://github.com/vlang/v/pull/6561 to work properly.
> window: make set_title() work

- canvas.v
- examples/group2.v
- examples/slider_textbox.v
- fmt_verify_all.vsh
- group.v
- label.v
- progressbar.v
- rectangle.v
- stack.v
- transition.v
- ui_darwin.c.v
- ui_windows.c.v
Requires https://github.com/vlang/v/pull/6638 to be green.
> format a few files and skip all that have errors

- dropdown.v
- fmt_verify_all.vsh
- menu.v
- slider.v
- switch.v
The failed macOS job is not related to my PR.
> format files were vfmt problems got resolved

- button.v
- checkbox.v
- examples/rectangles.v
- examples/users.v
- fmt_verify_all.vsh
- listbox.v
- picture.v
- radio.v
- textbox.v
- ui.v
- window.v
Actually I ran vfmt and reverted the lines that are faulty.
> warning fixes and partially formatting

- button.v
- checkbox.v
- fmt_verify_all.vsh
- picture.v
- ui_linux.c.v
Apply the vfmt fixes from https://github.com/vlang/v/pull/6874 and https://github.com/vlang/v/pull/6888.
@medvednikov the code-formatting job will pass if the second PR is merged
> apply recent vfmt fixes

- examples/webview.v
- webview/webview.v
- webview/webview_darwin.c.v
- webview/webview_linux.c.v
@medvednikov could you please verify that I broke nothing on macOS because I moved some code to a `_darwin.c.v` file.
The CI should be green after https://github.com/vlang/ui/pull/251 got merged.
> webview: linux implementation

- webview/webview_darwin.c.v
- window.v
This is necessary for https://github.com/vlang/v/pull/7267
> window: fix assigning int to pointer

- README.md
> readme: specify more linux deps

- window.v
need to detect right button clicked.
> window: set mouse button value to mouse event

- button.v
To change color of button when clicked.
> button: fix clicked state for color

- radio.v
- stack.v
this PR makes users.v example working....
> fix size for stack and radio

- README.md
https://github.com/vlang/ui/issues/284
> Fix Fedora Packages

- button.v
- canvas.v
- checkbox.v
- column.v
- dropdown.v
- easing.v
- examples/rgb_color.v
- group.v
- key.v
- label.v
- menu.v
- picture.v
- progressbar.v
- radio.v
- rectangle.v
- row.v
- stack.v
- switch.v
- textbox.v
- transition.v
- ui.v
- ui_darwin.c.v
- ui_darwin.m
- ui_linux.c.v
- ui_windows.c.v
- webview/webview.v
- webview/webview_darwin.m
- webview/webview_linux.c.v
- window.v
This PR updates the project's copyright year and applies an extra vfmt :).
> all: update copyright year

- examples/calculator_resizable.v
- examples/rectangles_resizable.v
- examples/rgb_color.v
- group.v
- stack.v
- ui.v
- ui_extra_debug.v
- ui_extra_debug_d_ui.v
- webview/webview.v
- window.v
* fullscreen mode
* name() interface commented by default to not pollute the other contributors
> fullscreen mode and no more name() in Layout interface

- progressbar.v
- window.v
after this [commit](https://github.com/vlang/v/commit/d4a05bebdeeaeddb1df7ccd9e4c57839a1978d67) window ui not working with sapp
i'm replaced events type to gg instead off sapp
> window: use gg types for Events instead of sapp

- button.v
- checkbox.v
- listbox.v
- menu.v
- progressbar.v
- stack.v
- switch.v
- textbox.v
- ui.v
Removes the ambiguity between `ui` as module name, and `ui` as
variable name, in checkbox.v and ui.v.
This prevented vfmt from working properly.
> fix vfmt job

- examples/grid.v
- grid.v
- window.v
There are a problems, such as cell length, that can be fixed in other commit
> grid: add grid widget with example

- ui.v
> open_url: windows implementation

- stack.v
- ui.v
- ui_extra_debug.v
- window.v
> use `mut` when smartcasting mutable interfaces

- button.v
On Android, to receive on_touch_down event for button pushed color change.
> button: fix event for android

- window.v
fixed MouseEvent.action for touch event.
> window:fix touch event

- ui_extra_scrollview.v
fixed subscribe_method() to unsubscribe_method()
> ui_extra_scrollview:fix cleanup

- radio.v
fixed that radio on_click doesn't work.
> fix radio on_click

- window.v
added missing events to Window.
> add window events

- slider.v
This PR fix error of float literals `20.`.
> ui: fix error of float literals `20.`

- README.md
> readme: works on Android

- ui_interface_drawtext.v
Needed for https://github.com/vlang/v/pull/12718 to pass
> textbox: use `fontstash` wrapper calls

- canvaslayout.v
This is in relation to the following `gg` PR https://github.com/vlang/v/pull/12827
> Changed draw_arc() to use draw_slice()

- checkbox.v
- transition.v
- ui.v
- window.v
Removed unused things and added some comments for further cleanup.
> clean up, remove unused

- button.v
- canvas.v
- canvaslayout.v
- checkbox.v
- column.v
- dropdown.v
- group.v
- key.v
- label.v
- menu.v
- picture.v
- progressbar.v
- radio.v
- rectangle.v
- row.v
- stack.v
- switch.v
- textbox.v
- transition.v
- ui.v
- ui_darwin.c.v
- ui_darwin.m
- ui_linux.c.v
- ui_windows.c.v
- window.v
> update copyright 2022

- easing.v
- extra_event_mngr.v
- key.v
- layout.v
- widget.v
- window.v
easing.v : update copyright
key.v : remove unused comment
widget.v, layout.v : re-ordering
window.v : re-ordering functions for readability
no addition, no remove, no edit in functionality
> cleanup re-ordaring

- extra_debug.v
- layout_stack.v
- window.v
This PR fix compile error for `if mut var in`.
> fix compile error for `if mut var in`

- interface_draw_device.v
- interface_scrollable.v
- layout_stack.v
- layout_window.v
- tool_event_mngr.v
- widget_menu.v
This should be cover all the unsafe comparisons due the compiler error added by the following PR https://github.com/vlang/v/pull/14462
Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>
> v: support new contraint of v with usafe {} block

- src/interface_adjustable.v
- src/tool_align.v
This PR fix generic fn call arg mismatch.
> fix generic fn call arg mismatch

- src/layout_group.v
- src/layout_stack.v
- src/layout_window.v
This PR fix error for array assign.
> fix error for array assign

- component/accordion.v
- examples/calculator.v
- examples/calculator_resizable.v
This PR fix error for array assign in accordion.v and examples.
> fix error for array assign in accordion.v and examples

- src/layout_window.v
This PR add `unsafe` for taking the address of map field.
> add 'unsafe' for taking the address of map field

- bin/vui_edit.v
- component/colorpalette.v
- component/filebrowser.v
- component/grid.v
- component/grid_data.v
- component/grid_tools.v
- src/layout_group.v
- src/layout_stack.v
- src/tool_message_dialog.v
- src/tool_mouse.v
- src/ui.v
- src/ui_default.c.v
- src/widget_checkbox.v
- src/widget_dropdown.v
- src/widget_grid.v
- src/widget_label.v
- src/widget_listbox.v
- src/widget_menu.v
- src/widget_picture.v
- src/widget_progressbar.v
- src/widget_radio.v
- src/widget_rectangle.v
- src/widget_slider.v
- src/widget_switch.v
- src/widget_textbox_textview.v
Since the CI check of a PR of v fails, please merge the PR first.
https://github.com/vlang/v/pull/15752
Thanks!   :)
> Fix the initialization of missing structure reference fields.

- libvg/svg.v
- src/widget_listbox.v
This PR change optional to result.
> all: change optional to result

- src/interface_layout.v
- src/interface_widget.v
Needed for https://github.com/vlang/v/pull/16214
> all: add mut to interface smartcast

- examples/7guis/timer.v
- examples/demo_logview.v
- src/ui.v
- src/ui_default.c.v
- src/widget_textbox.v
This PR fix textbox.draw_device() (fix #444, fix #483, fix #484).
> textbox: fix textbox.draw_device() (fix #444 #483 #484)

- src/extra_draw.v
- src/interface_drawtextwidget.v
`ctx.timage_pip` is no longer used due to the addition of the new `PipelineContainer`
Refer to vlang/v#16394
> Change `ctx.timage_pip` to `ctx.pipeline.alpha`

- v.mod
Updated license field in v.mod to reflect the re-licensing from GPL+Commercial to MIT.
> Updated license in v.mod

- src/layout_stack.v
Needed for https://github.com/vlang/v/pull/17917
> layout: rename `isize` to `i_size`

- examples/7guis/flightbooker.v
- src/extra_text_syntax.v
- src/textbox.v
> format needed files

- src/picture.v
Fixes this vab CI error: https://github.com/vlang/vab/actions/runs/4664056018/jobs/8255946380?pr=264
> examples: fix picture compilation error

- component/colorbox.v
- component/hideable.v
- src/interface_scrollable.v
Needed for https://github.com/vlang/v/pull/17923
> all: change `&Node(0)` to `&Node(unsafe { nil })`

- src/interface_layout.v
- src/layout_box.v
- src/layout_canvas.v
- src/layout_group.v
- src/stack.v
- src/subwindow.v
- src/window.v
eventbus generic type support : https://github.com/vlang/v/pull/18805#issue-1792657445
> eventbus: add generic support

- src/interface_application.v
- src/interface_build.v
- src/interface_clipping.v
- src/interface_drag_drop.v
- src/interface_draw_device.v
- src/interface_focusable.v
- src/interface_mouse_enter_leave.v
- src/interface_scrollable.v
- src/interface_themestyle.v
This PR make interfaces public.
> make interfaces public

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
residue from using a matrix setup steps and debugging while updating ci
> ci: remove unneeded residues

- README.md
temperature.v does not exist anymore.
> Replace example filename

- src/transition.v
for CI of https://github.com/vlang/v/pull/19830
> add unsafe block for deref assign

- src/interface_drag_drop.v
Fix for workflow break for V pr #21949
> fix struct field reference

- src/radio.v
Added Radio.set_values() function
> Update radio.v. Added set_values() function
